name: 'waypoint'
on: push

jobs:

  waypoint:
    runs-on: ubuntu-latest
    env:
      KUBERNETES_MASTER: ${{ secrets.KUBERNETES_MASTER }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: harbor.ravegrunt.com
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - uses: hashicorp/action-waypoint@v1
        name: Setup
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          waypoint_server_address: 'waypoint.ravegrunt.com:9701'
          waypoint_server_token: ${{ secrets.WAYPOINT_SERVER_TOKEN }}
          version: '0.1.5'
      - uses: hashicorp/action-waypoint@v1
        name: Build
        with:
          operation: build
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workspace: default
      - uses: hashicorp/action-waypoint@v1
        name: Deploy
        with:
          operation: deploy
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workspace: default
      - uses: hashicorp/action-waypoint@v1
        name: Release
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          operation: release
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workspace: default