name: 'waypoint'
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/action-waypoint
        name: Setup
        with:
          version: '0.1.2'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          waypoint_server_address: 'https://afa1be28c76944d15bff7969efc8f6c3-1774364022.us-east-1.elb.amazonaws.com:9701'
          waypoint_server_ui: 'https://afa1be28c76944d15bff7969efc8f6c3-1774364022.us-east-1.elb.amazonaws.com:9702'
          waypoint_server_token: ${{ secrets.WAYPOINT_SERVER_TOKEN }}
          workspace: default
      - uses: hashicorp/action-waypoint
        name: Build
        with:
          operation: build
          version: '0.1.2'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workspace: default
      - uses: hashicorp/action-waypoint
        name: Deploy
        with:
          operation: deploy
          version: '0.1.2'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workspace: default
      - uses: hashicorp/action-waypoint
        name: Release
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          operation: release
          version: '0.1.2'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workspace: default