name: 'waypoint'
on: push

jobs:

  waypoint:
    runs-on: ubuntu-latest
    env:
      KUBERNETES_MASTER: ${{ secrets.KUBERNETES_MASTER }}
      WAYPOINT_SERVER_TOKEN: ${{ secrets.WAYPOINT_SERVER_TOKEN }}
      WAYPOINT_SERVER_ADDR: waypoint.example.com:9701
      WAYPOINT_SERVER_TLS: 1
      WAYPOINT_SERVER_TLS_SKIP_VERIFY: 1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: harbor.ravegrunt.com
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - uses: hashicorp/action-setup-waypoint
        name: Waypoint Init
        with:
          version: '0.1.5'
      - run: waypoint init
      - run: waypoint build
