name: 'waypoint'
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      WAYPOINT_SERVER_TOKEN: ${{ secrets.WAYPOINT_SERVER_TOKEN }}
      WAYPOINT_SERVER_ADDR: afa1be28c76944d15bff7969efc8f6c3-1774364022.us-east-1.elb.amazonaws.com:9701
      WAYPOINT_SERVER_TLS: 1
      WAYPOINT_SERVER_TLS_SKIP_VERIFY: 1
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/action-setup-waypoint@b954572

        with:
          version: '0.1.0'
    - run: waypoint init
    - run: waypoint build