name: 'waypoint'
on: push

jobs:
  waypoint:
    runs-on: ubuntu-latest
    env:
      KUBERNETES_MASTER: ${{ secrets.KUBERNETES_MASTER }}
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: hashicorp/action-waypoint@main
        name: Setup
        with:
          version: '0.1.2'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          waypoint_server_address: ${{ secrets.WAYPOINT_SERVER }}
          waypoint_server_ui: ${{ secrets.WAYPOINT_URL }}
          waypoint_server_token: ${{ secrets.WAYPOINT_SERVER_TOKEN }}
          workspace: default
      - uses: hashicorp/action-waypoint@main
        name: Build
        with:
          operation: build
          version: '0.1.2'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workspace: default
      - uses: hashicorp/action-waypoint@main
        name: Deploy
        with:
          operation: deploy
          version: '0.1.2'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workspace: default
      - uses: hashicorp/action-waypoint@main
        name: Release
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          operation: release
          version: '0.1.2'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workspace: default