name: 'waypoint'
on: push

jobs:

  waypoint:
    runs-on: ubuntu-latest
    env:
      KUBERNETES_MASTER: ${{ secrets.KUBERNETES_MASTER }}
      WAYPOINT_SERVER_TOKEN: ${{ secrets.WAYPOINT_SERVER_TOKEN }}
      WAYPOINT_SERVER_ADDR: waypoint.ravegrunt.com:9701
      WAYPOINT_SERVER_TLS: 1
      WAYPOINT_SERVER_TLS_SKIP_VERIFY: 1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: harbor.ravegrunt.com
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: DO Kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.DO_CLUSTER_NAME }}
      
      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - uses: hashicorp/action-setup-waypoint@b6de610
        name: Waypoint Setup
        with:
          version: '0.1.5'
      - name: Waypoint Init
        run: waypoint init
      - name: Waypoint Build 
        run: waypoint build -workspace ${{ env.BRANCH_NAME }}
      - name: Waypoint Deploy and Release
        run: waypoint deploy -workspace ${{ env.BRANCH_NAME }}
